reporting: "on"
customCommands:
  - key: '<c-p>'
    command: "git push origin HEAD:refs/for/{{.CheckOutBranch.Name}}"
    context: ''
    loadingText: 'pushing...'
    description: "Creating a review in Gerrit"
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
gui:
  sidePanelWidth: 0.25
  theme:
    lightTheme: false
    activeBorderColor: [green, bold]
    inactiveBorderColor: [white]
    selectedLineBgColor: [default]
    selectedRangeBgColor: [default]
    cherryPickedCommitBgColor: [cyan]
    cherryPickedCommitFgColor: [blue]
    unstagedChangesColor: [red]
os:
  editCommand: 'nvim' # 设置你的默认编辑器
keybinding:
  universal:
    quit: 'q' # default
    return: '<esc>' # default
